apiVersion: argoproj.io/v1alpha1     # Specifies the API version for Argo CD resources
kind: Application                    # Defines this as an Argo CD Application resource
metadata:
  name: cert-manager                # Names this application "cert-manager"
  namespace: argocd                 # Places this resource in the "argocd" namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io  # Ensures proper cleanup when deleting this application
spec:                               # Begins the specification section
  project: infrastructure           # Associates this app with the "infrastructure" project
  source:                           # Defines where to get the application manifests
    repoURL: https://charts.jetstack.io  # URL to the Helm repository for cert-manager
    chart: cert-manager             # Name of the Helm chart to use
    targetRevision: v1.17.2         # Specific version of the chart to use
    helm:                           # Helm-specific configuration
      valueFiles:                   # List of value files to use
        - ../values.yaml            # Relative path to values file in your repo
  destination:                      # Defines where to deploy the application
    server: https://kubernetes.default.svc  # Deploys to the same cluster Argo CD runs in
    namespace: cert-manager         # Deploys cert-manager to its own namespace
  syncPolicy:                       # Defines how synchronization should work
    automated:                      # Enables automated sync
      prune: true                   # Removes resources that no longer exist in Git
      selfHeal: true                # Corrects drift by reapplying the desired state
    syncOptions:                    # Additional sync options
      - CreateNamespace=true        # Creates the cert-manager namespace if it doesn't exist